development:
  adapter: postgresql
  encoding: unicode
  database: entree_review_development
  pool: 5
  username: forrestwidmer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: entree_review_test
  pool: 5
  username: forrestwidmer
  password:

# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: entree_review_development
#   pool: 5
#   username: root
#   password: Mydogkills7710

# test:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: entree_review_test
#   pool: 5
#   username: root
#   password: Mydogkills7710

# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: entree_review_production
#   pool: 5
#   username: root
#   password: Mydogkills7710